theme: minima
#remote-theme: kitian616/jekyll-TeXt-theme
title: "Visualizations for #TidyTuesday datasets"
list_title: KLudges
description: My TidyTuesday kludges
author: Jesus M. Castagnetto
show_excerpts: true
minima:
    date_format: "%Y-%m-%d"
    social_links:
        twitter: jmcastagnetto
        github: jmcastagnetto
header_pages:
    - index.md
