remote_theme: aspirethemes/type
title: "Visualizations for #TidyTuesday datasets"
tagline: "ugly but works (TM)"
date_format: "%Y-%m-%d"
twitter: jmcastagnetto
github: jmcastagnetto
linkedIn: in/jesuscastagnetto
