remote_theme: thelehhman/texture

texture:
  title: "Visualizations for #TidyTuesday datasets"
  tagline: "ugly but works (TM)"
  date_format: "%Y-%m-%d"
  show_excerpts: true
  showNav: true
  style: blue
  social-links:
    twitter: jmcastagnetto
    github: jmcastagnetto
    linkedIn: in/jesuscastagnetto
