remote_theme: thelehhman/texture
show_excerpts: true
texture:
  title: "Visualizations for #TidyTuesday datasets"
  tagline: "ugly but works (TM)"
  date_format: "%Y-%m-%d"
  showNav: true
  style: green

  social_links:
    twitter: jmcastagnetto
    github: jmcastagnetto
    linkedIn: in/jesuscastagnetto
